# -*- coding: utf-8 -*-
"""Copy of deletealert.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kiAv8dgnJAYYz2kKyo_c5aqn-DPx0J_1
"""

from flask import Flask, request, jsonify

pip install Flask-SQLAlchemy

from flask_sqlalchemy import SQLAlchemy



pip install Flask-Marshmallow

from flask_marshmallow import Marshmallow

pip install Flask_restful

from flask_restful import Resource, Api

app = Flask(__name__) 
api = Api(app) 
app.config['SQLALCHEMY_DATABASE_URI'] = 'postgres:///Alerts.db' 
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False 
db = SQLAlchemy(app) 
ma = Marshmallow(app)

@staticmethod
def delete():
    try: id = request.args['alertid']
    except Exception as _: id = None

    if not id:
        returnjsonify({ 'Message': 'Must provide the alert ID' })

    alert = Alerts.query.get(id)
    db.session.delete(alert)
    db.session.commit()

    return jsonify({
        'Message': f'Alert {str(id)} deleted.'
    })