# -*- coding: utf-8 -*-
"""fetchalert.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z4ZA2iSGk21_WDyzHcSqnxfs0FttB8mI
"""

from flask import Flask, request, jsonify

pip install Flask-SQLAlchemy

from flask_sqlalchemy import SQLAlchemy



pip install Flask-Marshmallow

from flask_marshmallow import Marshmallow

pip install Flask_restful

from flask_restful import Resource, Api

app = Flask(__name__) 
api = Api(app) 
app.config['SQLALCHEMY_DATABASE_URI'] = 'postgres:///Alerts.db' 
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False 
db = SQLAlchemy(app) 
ma = Marshmallow(app)

@staticmethod
def delete():
    try: id = request.args['alertid']
    except Exception as _: id = None

    if not id:
        returnjsonify({ 'Message': 'Must provide the alert ID' })

    alert = Alerts.query.get(id)
    db.session.delete(alert)
    db.session.commit()

    return jsonify({
        'Message': f'Alert {str(id)} deleted.'
    })

@staticmethod
def fetchAllAlerts():
    try: id = request.args['alertid']
    except Exception as _: id = None

    if not id:
        alert = User.query.all()
        return jsonify(users_schema.dump(alerts))
    alert = Alerts.query.get(id)
    return jsonify(user_schema.dump(alert))

@staticmethod
def fetchAlertsByStatus():
  try: status = request.args['status']
  except Exception as _: status = None

  if not id:
      alert = User.query.all()
      return jsonify(users_schema.dump(alerts))
  alert = Alerts.query.get(status)
  return jsonify(user_schema.dump(alert))