# -*- coding: utf-8 -*-
"""sent mail.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RXg7PEbKFFr3fDx6Gi_uPbl2DFAtnT3y
"""

import smtplib, ssl

def sendEmail(userid, crypto, price):
  sender_email = "pranavtest123@rabbitmq.co.in"
  user = Users.query.get(userid)
  rec_email = user.email
  password = "test123";
  message = "Hii, " + user.username + "\nAlert!! current price of " + crypto + " reaches to " + price
  
  server = smtp.SMTP(rabbitmq@SERVER-IP)
  server.starttls()
  server.login(sender_email, password)
  print("Login success")
  server.sendmail(sender_email, reciever_email, message)
  print("Email has sent to ", rec_email)



